version: "3.9"
name: "ntnu-discord-notifier"

services:
  ntnu-discord-notifier:
    build:
      context: .
      target: notifier
    image: jacoblincool/ntnu-discord-notifier
    container_name: ntnu-discord-notifier
    env_file:
      - .env
    environment:
      - PORT=3000
    volumes:
      - ./data:/data
    ports:
      - 3000:3000
    restart: unless-stopped
